import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "../styles/Home.module.css"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles["header-container"]}>
          <div className={styles["header--title"]}>Site header</div>
          <Image
            className={styles["header-image"]}
            src="https://cdn.pixabay.com/photo/2016/10/24/22/43/dubai-1767540_1280.jpg"
            alt="background"
            width={100}
            height={100}
          />
          <div className={styles["header--text"]}>Dubai</div>
        </div>
      </main>

      <div className={styles["container-body"]}>
        <div className={styles["actions-buttons-wrapper"]}>
          <div className={styles["actions-buttons"]}>
            <button>Most Recent</button>
            <button>Best Questions</button>
            <button>Common Questions</button>
          </div>

          <button>Add Question</button>
        </div>
        <div className={styles["question-list"]}>
          <ul>
            <li>1. How to get from the Abu Dhabi to Dubai?</li>
            <li>2. What month is it best to come?</li>
            <li>3. What is the cheapest way to transit?</li>
          </ul>
        </div>
      </div>
    </>
  )
}
