import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import styles from "../styles/Home.module.css"
import { Collapse } from "react-collapse"
import { useEffect, useState } from "react"
import data from "../data.json"
import Link from "next/link"
export default function Home() {
  const [isOpen, setIsOpen] = useState<boolean[]>([])
  const questions = data
  useEffect(() => {
    setIsOpen(Array(data.length).fill(false))
  }, [data])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles["header-container"]}>
          <div className={styles["header--title"]}>Site header</div>
          <Image
            className={styles["header-image"]}
            src="https://cdn.pixabay.com/photo/2016/10/24/22/43/dubai-1767540_1280.jpg"
            alt="background"
            width={100}
            height={100}
          />
          <div className={styles["header--text"]}>Dubai</div>
        </div>
      </main>

      <div className={styles["container-body"]}>
        <div className={styles["actions-buttons-wrapper"]}>
          <div className={styles["actions-buttons"]}>
          <button>Common Questions</button>
            <button>Community</button>
            <button>Best Questions</button>
   
          </div>
        </div>
        <div className={styles["compose-question-container"]}>
          <input className={styles["compose-question-input"]} />
          <button>Add Question</button>
        </div>
        <div className={styles["questions"]}>
          <ul>
            {questions.map((question, i) => (
              <li key={question.title}>
                <div
                  className={styles["questions--item"]}
                  onClick={() =>
                    setIsOpen((prev) => {
                      const newData = [...prev]
                      newData[i] = !newData[i]
                      return newData
                    })
                  }
                >
                  {question.title}
                </div>
                <Collapse isOpened={isOpen[i]}>
                  <div className={styles["questions--item--answer"]}>
                    {question.content}
                    <div  className={styles["questions--item--answer--buttons-actions"]}>
                    👍 👎 <Link href={"#"}>Comment</Link>
                    </div>
                  </div>
                </Collapse>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </>
  )
}
